import type { Metadata } from "next";
import "./globals.css";
import { HeaderProvider } from "@/contexts/HeaderContext";
import { MealsProvider } from "@/contexts/MealsContext";

<meta
  name="format-detection"
  content="telephone=no, date=no, email=no, address=no"
/>


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeaderProvider>
          <MealsProvider>
        {children}
        </MealsProvider>
        </HeaderProvider>
      </body>
    </html>
  );
}
