import type { Metadata } from "next";
import "./globals.css";
import { HeaderProvider } from "@/contexts/HeaderContext";
import { MealsProvider } from "@/contexts/MealsContext";
import { InputBalancesProvider } from "@/contexts/InputBalancesContext";
import { CalculateProvider } from "@/contexts/CalculateContext";
import { RiceProvider } from "@/contexts/RiceContext";

<meta
  name="format-detection"
  content="telephone=no, date=no, email=no, address=no"
/>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeaderProvider>
          <MealsProvider>
            <InputBalancesProvider>
              <CalculateProvider>
                <RiceProvider>{children}</RiceProvider>
              </CalculateProvider>
            </InputBalancesProvider>
          </MealsProvider>
        </HeaderProvider>
      </body>
    </html>
  );
}
